### ISSUE TITLE
No signature of method: static cm.nexus.cleanup.ConfigReader.readConfig() is applicable for argument types

### ISSUE THREAD

**Issue by miloske85** [tallandtree/nxrm3-cleaning#1]
After setting up according to instructions from README and double-checking all paths and the format of YAML file, I get the following error. 
[nexus_cleanup.txt](https://github.com/tallandtree/nxrm3-cleaning/files/3799446/nexus_cleanup.txt)
Tried on nexus 3.15 and then upgraded to nexus 3.19. Error was the same in both cases.

Looking at the code, although I don't know Groovy, I see that in ConfigReader.groovy there is
`static Config readConfig(Logger log, String path)`
which indeed doesn't match the method signature from the README file (the nexus task part), where it says:
`def config = configReaderClass.readConfig("/opt/sonatype/sonatype-work/nexus3/cm/scripts/resources")`

I get the same error when I comment out:
```
def cleaner =  deleteAssetsClass...
cleaner.dryRun()
```

**Comment by tallandtree** [comment]
Ah, yes, the example is wrong. Sorry I didn't respond earlier. 
It should be:
```
def config = configReaderClass.readConfig(log, "/opt/sonatype/sonatype-work/nexus3/cm/scripts/resources");
```
I'll update the documentation.

**Comment by tallandtree** [comment]
Should work now according to the documentation.

**Comment by tallandtree** [comment]
Shoul work now according to the documentation.
